CREATE TABLE IF NOT EXISTS warehouse_workers_final (worker_id TEXT PRIMARY KEY, name TEXT, role TEXT, shift TEXT, status TEXT, tasks_completed INTEGER, age INTEGER, gender TEXT);

INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W001', 'Naveen Gowda', 'Receiving Associate', 'Afternoon', 'On Task', '440', '34', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W002', 'Gauri Bhosale', 'Shipping Associate', 'Afternoon', 'Available', '883', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W003', 'Richa Singh', 'Loader', 'Night', 'Available', '490', '38', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W004', 'Nikhil Hegde', 'Quality Inspector', 'Afternoon', 'Available', '326', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W005', 'Yogesh Patil', 'Forklift Operator', 'Morning', 'Available', '272', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W006', 'Pradeep Rao', 'Packer', 'Night', 'Available', '406', '22', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W007', 'Saurabh Yadav', 'Receiving Associate', 'Night', 'On Break', '567', '38', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W008', 'Asha Hegde', 'Picker', 'Afternoon', 'Available', '738', '34', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W009', 'Pratik Bhosale', 'Shift Supervisor', 'Afternoon', 'On Task', '968', '23', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W010', 'Aryan Mishra', 'Loader', 'Morning', 'On Task', '168', '37', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W011', 'Suresh Gowda', 'Shift Supervisor', 'Night', 'Available', '777', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W012', 'Swapnil Pawar', 'Quality Inspector', 'Morning', 'Available', '367', '34', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W013', 'Sumit More', 'Loader', 'Night', 'On Task', '465', '32', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W014', 'Harish Murthy', 'Inventory Clerk', 'Morning', 'On Break', '46', '39', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W015', 'Rahul Shetty', 'Inventory Clerk', 'Night', 'On Task', '873', '37', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W016', 'Prashanth Naik', 'Receiving Associate', 'Night', 'On Task', '745', '29', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W017', 'Shruti Sharma', 'Forklift Operator', 'Morning', 'On Task', '819', '34', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W018', 'Pratik Bhosale', 'Shift Supervisor', 'Night', 'On Task', '18', '34', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W019', 'Pooja Deshpande', 'Forklift Operator', 'Afternoon', 'Available', '158', '30', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W020', 'Monika Yadav', 'Shift Supervisor', 'Night', 'On Task', '25', '22', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W021', 'Prashanth Naik', 'Forklift Operator', 'Morning', 'On Task', '882', '37', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W022', 'Abhishek Gupta', 'Packer', 'Morning', 'Off Shift', '554', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W023', 'Abhishek Gupta', 'Shipping Associate', 'Morning', 'Available', '301', '36', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W024', 'Pradeep Rao', 'Shift Supervisor', 'Morning', 'On Task', '359', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W025', 'Sanjay Kumar', 'Inventory Clerk', 'Morning', 'On Task', '897', '29', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W026', 'Meena Murthy', 'Shift Supervisor', 'Night', 'On Task', '309', '22', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W027', 'Nikhil Hegde', 'Shipping Associate', 'Morning', 'On Task', '228', '37', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W028', 'Rahul Shetty', 'Quality Inspector', 'Afternoon', 'On Break', '757', '23', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W029', 'Aditi Kulkarni', 'Packer', 'Night', 'Available', '203', '31', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W030', 'Swati Verma', 'Shipping Associate', 'Night', 'On Task', '413', '30', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W031', 'Rishabh Agarwal', 'Shipping Associate', 'Afternoon', 'On Break', '303', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W032', 'Harish Murthy', 'Shift Supervisor', 'Night', 'Available', '134', '23', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W033', 'Deepak Naik', 'Inventory Clerk', 'Morning', 'Available', '940', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W034', 'Ramesh Nair', 'Unloader', 'Morning', 'On Break', '733', '40', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W035', 'Mrunali Bhosale', 'Unloader', 'Morning', 'On Task', '567', '37', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W036', 'Lakshmi Reddy', 'Receiving Associate', 'Night', 'Available', '210', '30', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W037', 'Ashish Gupta', 'Inventory Clerk', 'Morning', 'On Break', '577', '29', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W038', 'Neha Agarwal', 'Packer', 'Afternoon', 'Available', '257', '34', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W039', 'Rutuja Kulkarni', 'Unloader', 'Morning', 'Off Shift', '756', '29', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W040', 'Omkar Pawar', 'Inventory Clerk', 'Night', 'On Task', '153', '30', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W041', 'Anil Murthy', 'Unloader', 'Afternoon', 'On Break', '429', '36', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W042', 'Kunal Joshi', 'Shipping Associate', 'Night', 'Available', '900', '23', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W043', 'Prashanth Naik', 'Receiving Associate', 'Afternoon', 'Available', '822', '30', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W044', 'Ravi Kumar', 'Picker', 'Night', 'Available', '745', '36', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W045', 'Kedar Bhosale', 'Quality Inspector', 'Afternoon', 'On Break', '277', '39', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W046', 'Usha Rao', 'Loader', 'Night', 'Available', '917', '23', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W047', 'Ashish Gupta', 'Forklift Operator', 'Night', 'Off Shift', '254', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W048', 'Deepak Singh', 'Inventory Clerk', 'Night', 'On Task', '598', '35', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W049', 'Manish Sharma', 'Receiving Associate', 'Afternoon', 'On Task', '519', '34', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W050', 'Sowmya Shetty', 'Packer', 'Afternoon', 'Available', '794', '30', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W051', 'Kartik Tiwari', 'Quality Inspector', 'Morning', 'Available', '888', '34', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W052', 'Sonal Sawant', 'Inventory Clerk', 'Night', 'Available', '295', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W053', 'Deepa Nair', 'Loader', 'Morning', 'Available', '34', '34', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W054', 'Pooja Naik', 'Shift Supervisor', 'Night', 'Available', '413', '31', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W055', 'Nisha Singh', 'Inventory Clerk', 'Night', 'On Break', '228', '31', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W056', 'Abhishek Gupta', 'Inventory Clerk', 'Afternoon', 'Available', '794', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W057', 'Ramesh Nair', 'Receiving Associate', 'Night', 'Available', '68', '38', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W058', 'Manasi Shinde', 'Shift Supervisor', 'Morning', 'Available', '534', '39', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W059', 'Pratik Bhosale', 'Packer', 'Morning', 'Available', '552', '32', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W060', 'Aniket Shinde', 'Picker', 'Afternoon', 'Available', '54', '36', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W061', 'Manish Sharma', 'Shipping Associate', 'Morning', 'Available', '941', '29', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W062', 'Vijay Rao', 'Shipping Associate', 'Afternoon', 'On Break', '979', '30', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W063', 'Harish Murthy', 'Forklift Operator', 'Night', 'Available', '808', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W064', 'Pallavi Deshmukh', 'Shipping Associate', 'Afternoon', 'On Task', '507', '22', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W065', 'Ajay Reddy', 'Loader', 'Afternoon', 'On Task', '234', '34', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W066', 'Anil Murthy', 'Shift Supervisor', 'Morning', 'On Task', '145', '40', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W067', 'Ravi Kumar', 'Shift Supervisor', 'Night', 'On Task', '508', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W068', 'Kunal Joshi', 'Shift Supervisor', 'Morning', 'Available', '523', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W069', 'Shruti Sharma', 'Loader', 'Night', 'Available', '917', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W070', 'Asha Hegde', 'Unloader', 'Morning', 'Available', '171', '40', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W071', 'Keerthi Murthy', 'Unloader', 'Morning', 'Available', '331', '23', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W072', 'Naveen Gowda', 'Picker', 'Night', 'Available', '1', '31', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W073', 'Mrunali Bhosale', 'Loader', 'Night', 'On Task', '962', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W074', 'Naveen Gowda', 'Receiving Associate', 'Night', 'On Task', '114', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W075', 'Anjali Gupta', 'Forklift Operator', 'Morning', 'On Task', '679', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W076', 'Deepak Naik', 'Receiving Associate', 'Night', 'Available', '702', '40', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W077', 'Suma Naik', 'Unloader', 'Morning', 'On Task', '559', '23', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W078', 'Bhavana Kumar', 'Inventory Clerk', 'Morning', 'On Task', '384', '23', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W079', 'Suresh Gowda', 'Loader', 'Morning', 'On Break', '499', '39', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W080', 'Pankaj Agarwal', 'Quality Inspector', 'Night', 'On Task', '15', '37', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W081', 'Amit Kulkarni', 'Unloader', 'Night', 'On Task', '83', '38', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W082', 'Deepa Nair', 'Packer', 'Afternoon', 'Off Shift', '953', '31', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W083', 'Naveen Gowda', 'Packer', 'Afternoon', 'Available', '623', '38', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W084', 'Priya Nair', 'Unloader', 'Morning', 'Available', '650', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W085', 'Vidya Sharma', 'Shift Supervisor', 'Night', 'Available', '602', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W086', 'Mahesh Kulkarni', 'Quality Inspector', 'Morning', 'Off Shift', '967', '36', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W087', 'Neha Pawar', 'Unloader', 'Night', 'Available', '81', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W088', 'Pallavi Deshmukh', 'Unloader', 'Morning', 'Off Shift', '259', '32', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W089', 'Ravi Kumar', 'Quality Inspector', 'Night', 'Available', '639', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W090', 'Shubham Yadav', 'Quality Inspector', 'Afternoon', 'On Task', '104', '32', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W091', 'Suresh Gowda', 'Packer', 'Morning', 'On Task', '145', '30', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W092', 'Rajesh Verma', 'Shipping Associate', 'Night', 'On Break', '602', '22', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W093', 'Preeti Tiwari', 'Picker', 'Night', 'Available', '809', '34', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W094', 'Pankaj Agarwal', 'Quality Inspector', 'Afternoon', 'Available', '934', '36', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W095', 'Tejas Kumar', 'Quality Inspector', 'Night', 'On Task', '815', '39', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W096', 'Kiran Nair', 'Inventory Clerk', 'Morning', 'Available', '240', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W097', 'Lakshmi Reddy', 'Shift Supervisor', 'Night', 'On Task', '213', '31', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W098', 'Anil Murthy', 'Loader', 'Afternoon', 'On Task', '240', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W099', 'Nandini Gowda', 'Unloader', 'Night', 'On Task', '3', '29', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W100', 'Nandini Gowda', 'Inventory Clerk', 'Morning', 'Available', '29', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W101', 'Swapnil Pawar', 'Inventory Clerk', 'Morning', 'On Task', '729', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W102', 'Aniket Shinde', 'Unloader', 'Morning', 'On Task', '907', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W103', 'Isha Tiwari', 'Receiving Associate', 'Afternoon', 'On Task', '221', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W104', 'Komal Shinde', 'Quality Inspector', 'Night', 'On Task', '78', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W105', 'Kartik Tiwari', 'Quality Inspector', 'Morning', 'On Task', '261', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W106', 'Mrunali Bhosale', 'Unloader', 'Morning', 'Available', '60', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W107', 'Kartik Tiwari', 'Shipping Associate', 'Afternoon', 'Available', '623', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W108', 'Tejas Kumar', 'Unloader', 'Morning', 'Available', '699', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W109', 'Akshay Sawant', 'Picker', 'Night', 'Available', '946', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W110', 'Keerthi Murthy', 'Inventory Clerk', 'Afternoon', 'On Task', '917', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W111', 'Suma Naik', 'Forklift Operator', 'Night', 'Available', '737', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W112', 'Manasi Shinde', 'Forklift Operator', 'Afternoon', 'Available', '168', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W113', 'Naveen Gowda', 'Shipping Associate', 'Morning', 'Available', '619', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W114', 'Ajay Reddy', 'Shipping Associate', 'Morning', 'Available', '839', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W115', 'Rishabh Agarwal', 'Inventory Clerk', 'Afternoon', 'On Task', '916', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W116', 'Ashwini Sawant', 'Loader', 'Afternoon', 'On Task', '248', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W117', 'Prashanth Naik', 'Shift Supervisor', 'Night', 'Available', '899', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W118', 'Vivek Mishra', 'Inventory Clerk', 'Morning', 'On Task', '201', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W119', 'Swathi Shetty', 'Picker', 'Afternoon', 'Available', '53', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W120', 'Vivek Mishra', 'Forklift Operator', 'Night', 'Available', '356', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W121', 'Meena Murthy', 'Receiving Associate', 'Night', 'On Task', '455', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W122', 'Aryan Mishra', 'Packer', 'Morning', 'Available', '35', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W123', 'Sakshi Gupta', 'Forklift Operator', 'Night', 'Available', '45', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W124', 'Vijay Rao', 'Picker', 'Afternoon', 'On Break', '233', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W125', 'Rekha Kumar', 'Packer', 'Morning', 'Available', '126', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W126', 'Gaurav Deshpande', 'Packer', 'Morning', 'Available', '3', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W127', 'Harish Murthy', 'Receiving Associate', 'Afternoon', 'On Break', '402', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W128', 'Yogesh Patil', 'Unloader', 'Afternoon', 'On Break', '147', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W129', 'Ajay Reddy', 'Unloader', 'Afternoon', 'Available', '291', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W130', 'Rohan Deshmukh', 'Shift Supervisor', 'Night', 'Available', '977', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W131', 'Asha Hegde', 'Packer', 'Afternoon', 'Available', '168', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W132', 'Sanjay Kumar', 'Forklift Operator', 'Morning', 'Available', '689', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W133', 'Shubham Yadav', 'Shift Supervisor', 'Night', 'On Task', '314', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W134', 'Ganesh Hegde', 'Receiving Associate', 'Afternoon', 'On Break', '317', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W135', 'Ashish Gupta', 'Forklift Operator', 'Night', 'Available', '84', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W136', 'Neeraj Tiwari', 'Inventory Clerk', 'Afternoon', 'Available', '748', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W137', 'Simran Srivastava', 'Inventory Clerk', 'Afternoon', 'Available', '181', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W138', 'Aditya Sawant', 'Inventory Clerk', 'Afternoon', 'Available', '638', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W139', 'Ashish Gupta', 'Picker', 'Afternoon', 'Available', '827', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W140', 'Rahul Shetty', 'Loader', 'Morning', 'Available', '452', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W141', 'Pankaj Agarwal', 'Quality Inspector', 'Night', 'On Break', '600', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W142', 'Mrunali Bhosale', 'Forklift Operator', 'Night', 'On Break', '366', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W143', 'Sakshi Gupta', 'Receiving Associate', 'Afternoon', 'Available', '416', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W144', 'Deepak Naik', 'Shift Supervisor', 'Morning', 'On Task', '544', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W145', 'Vidya Sharma', 'Unloader', 'Morning', 'Available', '877', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W146', 'Vrushali Patil', 'Shipping Associate', 'Morning', 'On Task', '210', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W147', 'Ganesh Hegde', 'Picker', 'Afternoon', 'On Task', '770', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W148', 'Vaibhav Deshpande', 'Shift Supervisor', 'Night', 'On Task', '377', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W149', 'Rahul Shetty', 'Loader', 'Night', 'Available', '191', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W150', 'Sumit More', 'Packer', 'Night', 'On Break', '486', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W151', 'Richa Singh', 'Packer', 'Afternoon', 'Available', '485', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W152', 'Ganesh Hegde', 'Packer', 'Afternoon', 'Available', '536', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W153', 'Madhuri More', 'Picker', 'Morning', 'On Break', '503', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W154', 'Sanjay Kumar', 'Receiving Associate', 'Night', 'Available', '317', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W155', 'Aditi Kulkarni', 'Loader', 'Morning', 'Available', '1', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W156', 'Ritu Sharma', 'Packer', 'Afternoon', 'On Task', '575', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W157', 'Swathi Shetty', 'Forklift Operator', 'Night', 'Available', '878', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W158', 'Kiran Nair', 'Receiving Associate', 'Night', 'On Task', '534', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W159', 'Ramesh Nair', 'Packer', 'Night', 'Available', '759', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W160', 'Anil Murthy', 'Quality Inspector', 'Night', 'Available', '657', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W161', 'Suma Naik', 'Quality Inspector', 'Night', 'Available', '381', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W162', 'Lakshmi Reddy', 'Picker', 'Afternoon', 'Available', '916', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W163', 'Sakshi Gupta', 'Shift Supervisor', 'Afternoon', 'On Task', '210', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W164', 'Vijay Rao', 'Forklift Operator', 'Night', 'Available', '54', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W165', 'Lokesh Shetty', 'Shipping Associate', 'Night', 'Off Shift', '4', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W166', 'Kiran Nair', 'Unloader', 'Afternoon', 'On Task', '707', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W167', 'Suresh Gowda', 'Shift Supervisor', 'Afternoon', 'On Break', '124', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W168', 'Vijay Rao', 'Quality Inspector', 'Afternoon', 'Available', '811', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W169', 'Suresh Gowda', 'Picker', 'Morning', 'Available', '242', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W170', 'Harsh Verma', 'Packer', 'Night', 'On Task', '853', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W171', 'Shweta Joshi', 'Inventory Clerk', 'Afternoon', 'On Break', '0', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W172', 'Sachin Deshmukh', 'Forklift Operator', 'Night', 'On Task', '377', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W173', 'Swapnali Pawar', 'Unloader', 'Night', 'On Task', '803', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W174', 'Ananya Hegde', 'Shipping Associate', 'Morning', 'On Break', '294', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W175', 'Ajay Reddy', 'Unloader', 'Afternoon', 'Available', '951', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W176', 'Nikhil Hegde', 'Receiving Associate', 'Morning', 'On Break', '257', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W177', 'Suresh Gowda', 'Shipping Associate', 'Night', 'Available', '911', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W178', 'Ramesh Nair', 'Packer', 'Afternoon', 'Available', '41', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W179', 'Monika Yadav', 'Shipping Associate', 'Morning', 'Available', '245', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W180', 'Kiran Nair', 'Loader', 'Night', 'On Task', '437', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W181', 'Kunal Joshi', 'Receiving Associate', 'Afternoon', 'Available', '902', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W182', 'Sanket Shinde', 'Shift Supervisor', 'Morning', 'On Task', '766', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W183', 'Naveen Gowda', 'Packer', 'Afternoon', 'On Task', '130', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W184', 'Tarun Srivastava', 'Shift Supervisor', 'Morning', 'On Task', '661', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W185', 'Kavita Mishra', 'Receiving Associate', 'Afternoon', 'Available', '40', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W186', 'Sumit More', 'Shipping Associate', 'Afternoon', 'Available', '49', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W187', 'Kavita Mishra', 'Unloader', 'Night', 'On Task', '357', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W188', 'Nisha Singh', 'Forklift Operator', 'Night', 'On Task', '775', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W189', 'Rajesh Verma', 'Shipping Associate', 'Night', 'On Task', '335', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W190', 'Harish Murthy', 'Picker', 'Afternoon', 'Available', '318', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W191', 'Ajay Reddy', 'Packer', 'Morning', 'Available', '659', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W192', 'Kiran Nair', 'Forklift Operator', 'Afternoon', 'Available', '678', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W193', 'Vijay Rao', 'Unloader', 'Afternoon', 'On Break', '711', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W194', 'Bhavana Kumar', 'Loader', 'Afternoon', 'Available', '317', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W195', 'Sonia Joshi', 'Picker', 'Morning', 'Available', '492', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W196', 'Dinesh Jadhav', 'Receiving Associate', 'Night', 'On Task', '101', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W197', 'Rohan Deshmukh', 'Shipping Associate', 'Afternoon', 'Available', '152', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W198', 'Monika Yadav', 'Shipping Associate', 'Morning', 'On Task', '861', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W199', 'Rahul Shetty', 'Shift Supervisor', 'Night', 'On Task', '554', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W200', 'Pratik Bhosale', 'Quality Inspector', 'Morning', 'Available', '301', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W201', 'Sonal Sawant', 'Loader', 'Morning', 'Available', '356', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W202', 'Suresh Gowda', 'Picker', 'Night', 'On Task', '612', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W203', 'Arjun Reddy', 'Unloader', 'Afternoon', 'Available', '377', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W204', 'Neha Pawar', 'Receiving Associate', 'Night', 'Available', '866', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W205', 'Vikram Singh', 'Picker', 'Afternoon', 'On Task', '544', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W206', 'Gauri Bhosale', 'Loader', 'Morning', 'Available', '560', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W207', 'Kiran Nair', 'Picker', 'Night', 'On Break', '576', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W208', 'Rohit Patil', 'Unloader', 'Morning', 'On Task', '45', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W209', 'Lokesh Shetty', 'Receiving Associate', 'Morning', 'Available', '932', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W210', 'Ajay Reddy', 'Loader', 'Morning', 'Available', '64', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W211', 'Harish Murthy', 'Receiving Associate', 'Morning', 'Available', '367', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W212', 'Manasi Shinde', 'Inventory Clerk', 'Morning', 'On Task', '252', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W213', 'Pooja Naik', 'Receiving Associate', 'Afternoon', 'Available', '791', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W214', 'Swapnil Pawar', 'Quality Inspector', 'Night', 'On Task', '134', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W215', 'Nandini Gowda', 'Receiving Associate', 'Morning', 'On Break', '761', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W216', 'Anjali Gupta', 'Forklift Operator', 'Morning', 'On Break', '959', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W217', 'Ashish Gupta', 'Quality Inspector', 'Night', 'Available', '563', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W218', 'Rajesh Verma', 'Shipping Associate', 'Night', 'Available', '623', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W219', 'Gauri Bhosale', 'Picker', 'Night', 'Off Shift', '819', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W220', 'Ashish Gupta', 'Unloader', 'Night', 'Available', '666', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W221', 'Sanjay Kumar', 'Quality Inspector', 'Afternoon', 'On Task', '105', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W222', 'Nitin Jadhav', 'Unloader', 'Afternoon', 'On Task', '896', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W223', 'Meena Murthy', 'Loader', 'Morning', 'Available', '340', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W224', 'Prashanth Naik', 'Unloader', 'Morning', 'Available', '416', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W225', 'Sonal Sawant', 'Forklift Operator', 'Night', 'Available', '312', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W226', 'Nitin Jadhav', 'Loader', 'Afternoon', 'Available', '56', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W227', 'Swapnali Pawar', 'Packer', 'Morning', 'Available', '238', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W228', 'Pradeep Rao', 'Quality Inspector', 'Afternoon', 'Available', '688', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W229', 'Gauri Bhosale', 'Shipping Associate', 'Morning', 'Available', '113', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W230', 'Pratik Bhosale', 'Unloader', 'Morning', 'Available', '236', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W231', 'Sumit More', 'Packer', 'Afternoon', 'On Task', '47', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W232', 'Sunita Agarwal', 'Shift Supervisor', 'Night', 'On Task', '779', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W233', 'Deepak Naik', 'Picker', 'Morning', 'Available', '253', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W234', 'Rahul Shetty', 'Forklift Operator', 'Afternoon', 'Available', '287', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W235', 'Rutuja Kulkarni', 'Loader', 'Morning', 'On Break', '790', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W236', 'Rahul Shetty', 'Inventory Clerk', 'Night', 'On Task', '472', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W237', 'Sunita Agarwal', 'Shipping Associate', 'Night', 'On Task', '741', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W238', 'Vidya Sharma', 'Forklift Operator', 'Night', 'On Break', '137', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W239', 'Neeraj Tiwari', 'Inventory Clerk', 'Afternoon', 'On Task', '153', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W240', 'Swapnali Pawar', 'Receiving Associate', 'Morning', 'Available', '929', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W241', 'Mahesh Kulkarni', 'Loader', 'Night', 'Available', '541', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W242', 'Rajesh Verma', 'Packer', 'Night', 'On Task', '148', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W243', 'Komal Shinde', 'Quality Inspector', 'Afternoon', 'Available', '493', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W244', 'Usha Rao', 'Packer', 'Night', 'Available', '385', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W245', 'Kiran Nair', 'Forklift Operator', 'Morning', 'Available', '465', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W246', 'Neha Pawar', 'Picker', 'Afternoon', 'Available', '104', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W247', 'Tejas Kumar', 'Unloader', 'Night', 'On Task', '220', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W248', 'Rahul Shetty', 'Loader', 'Afternoon', 'Available', '340', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W249', 'Rohit Patil', 'Picker', 'Night', 'Available', '695', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W250', 'Sunita Agarwal', 'Quality Inspector', 'Afternoon', 'Available', '874', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W251', 'Rekha Kumar', 'Forklift Operator', 'Afternoon', 'Off Shift', '166', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W252', 'Manoj Sharma', 'Picker', 'Afternoon', 'Available', '461', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W253', 'Vijay Rao', 'Shift Supervisor', 'Afternoon', 'Available', '553', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W254', 'Deepak Naik', 'Quality Inspector', 'Afternoon', 'Available', '190', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W255', 'Tanya Yadav', 'Inventory Clerk', 'Afternoon', 'On Break', '570', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W256', 'Omkar Pawar', 'Receiving Associate', 'Morning', 'Available', '138', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W257', 'Gauri Bhosale', 'Unloader', 'Afternoon', 'Available', '368', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W258', 'Jyoti Verma', 'Shift Supervisor', 'Afternoon', 'Available', '928', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W259', 'Sunita Agarwal', 'Inventory Clerk', 'Morning', 'On Task', '375', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W260', 'Sonia Joshi', 'Loader', 'Night', 'On Task', '669', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W261', 'Suresh Gowda', 'Quality Inspector', 'Night', 'On Task', '79', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W262', 'Shraddha Jadhav', 'Receiving Associate', 'Night', 'On Task', '640', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W263', 'Sanjay Kumar', 'Quality Inspector', 'Morning', 'Available', '40', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W264', 'Amit Kulkarni', 'Receiving Associate', 'Night', 'Available', '26', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W265', 'Vijay Rao', 'Shift Supervisor', 'Morning', 'On Task', '856', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W266', 'Aryan Mishra', 'Packer', 'Afternoon', 'On Task', '845', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W267', 'Tanya Yadav', 'Forklift Operator', 'Morning', 'Available', '445', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W268', 'Harish Murthy', 'Shipping Associate', 'Night', 'On Task', '238', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W269', 'Ramesh Nair', 'Forklift Operator', 'Afternoon', 'On Task', '940', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W270', 'Nandini Gowda', 'Picker', 'Afternoon', 'Available', '212', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W271', 'Sneha Patil', 'Shift Supervisor', 'Morning', 'On Break', '368', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W272', 'Tanya Yadav', 'Loader', 'Afternoon', 'Available', '279', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W273', 'Akshay Sawant', 'Loader', 'Night', 'On Task', '7', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W274', 'Shubham Yadav', 'Picker', 'Night', 'Available', '231', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W275', 'Nandini Gowda', 'Quality Inspector', 'Morning', 'On Task', '69', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W276', 'Vrushali Patil', 'Inventory Clerk', 'Afternoon', 'On Break', '554', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W277', 'Kiran Nair', 'Receiving Associate', 'Afternoon', 'On Task', '434', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W278', 'Pradeep Rao', 'Unloader', 'Morning', 'Available', '362', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W279', 'Sunita Agarwal', 'Loader', 'Night', 'Available', '730', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W280', 'Manish Sharma', 'Receiving Associate', 'Night', 'On Task', '194', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W281', 'Manoj Sharma', 'Receiving Associate', 'Morning', 'Available', '959', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W282', 'Harsh Verma', 'Unloader', 'Morning', 'Available', '932', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W283', 'Shraddha Jadhav', 'Shift Supervisor', 'Night', 'On Break', '885', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W284', 'Tarun Srivastava', 'Shift Supervisor', 'Afternoon', 'Off Shift', '452', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W285', 'Asha Hegde', 'Loader', 'Night', 'On Task', '414', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W286', 'Sunita Agarwal', 'Unloader', 'Afternoon', 'Available', '250', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W287', 'Nikhil Hegde', 'Picker', 'Afternoon', 'On Break', '914', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W288', 'Ravi Kumar', 'Shipping Associate', 'Night', 'Available', '70', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W289', 'Rutuja Kulkarni', 'Packer', 'Afternoon', 'Available', '607', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W290', 'Ajay Reddy', 'Picker', 'Night', 'On Task', '267', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W291', 'Vijay Rao', 'Forklift Operator', 'Night', 'On Task', '689', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W292', 'Sunita Agarwal', 'Shipping Associate', 'Night', 'On Task', '671', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W293', 'Saurabh Yadav', 'Shipping Associate', 'Night', 'Off Shift', '522', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W294', 'Poonam Mishra', 'Picker', 'Afternoon', 'On Task', '40', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W295', 'Deepak Singh', 'Shipping Associate', 'Morning', 'Available', '694', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W296', 'Kavya Rao', 'Picker', 'Night', 'Available', '967', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W297', 'Amit Kulkarni', 'Inventory Clerk', 'Afternoon', 'Available', '636', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W298', 'Suma Naik', 'Shipping Associate', 'Afternoon', 'On Task', '590', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W299', 'Ramesh Nair', 'Unloader', 'Night', 'On Task', '622', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W300', 'Sanjay Kumar', 'Inventory Clerk', 'Afternoon', 'Available', '112', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W301', 'Ajay Reddy', 'Loader', 'Night', 'Available', '482', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W302', 'Sakshi Gupta', 'Inventory Clerk', 'Night', 'Available', '581', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W303', 'Shweta Joshi', 'Receiving Associate', 'Afternoon', 'Available', '435', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W304', 'Pooja Deshpande', 'Inventory Clerk', 'Morning', 'Available', '378', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W305', 'Kunal Joshi', 'Picker', 'Morning', 'On Break', '557', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W306', 'Simran Srivastava', 'Shift Supervisor', 'Afternoon', 'Available', '409', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W307', 'Kartik Tiwari', 'Loader', 'Afternoon', 'On Break', '87', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W308', 'Sachin Deshmukh', 'Receiving Associate', 'Night', 'Available', '797', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W309', 'Naina Srivastava', 'Loader', 'Night', 'Available', '228', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W310', 'Ramesh Nair', 'Inventory Clerk', 'Afternoon', 'Available', '964', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W311', 'Tejashree More', 'Receiving Associate', 'Afternoon', 'Available', '736', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W312', 'Vidya Sharma', 'Shipping Associate', 'Morning', 'On Task', '196', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W313', 'Aditya Sawant', 'Shipping Associate', 'Night', 'On Task', '566', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W314', 'Lokesh Shetty', 'Unloader', 'Night', 'Available', '807', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W315', 'Neha Pawar', 'Packer', 'Morning', 'On Task', '70', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W316', 'Mahesh Kulkarni', 'Receiving Associate', 'Morning', 'On Task', '89', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W317', 'Amit Kulkarni', 'Inventory Clerk', 'Night', 'Available', '42', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W318', 'Shraddha Jadhav', 'Inventory Clerk', 'Afternoon', 'On Task', '595', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W319', 'Sonal Sawant', 'Forklift Operator', 'Night', 'On Task', '327', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W320', 'Vijay Rao', 'Inventory Clerk', 'Night', 'On Task', '848', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W321', 'Suma Naik', 'Forklift Operator', 'Afternoon', 'On Break', '965', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W322', 'Omkar Pawar', 'Shipping Associate', 'Night', 'On Task', '416', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W323', 'Sonia Joshi', 'Unloader', 'Morning', 'Available', '420', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W324', 'Pradeep Rao', 'Unloader', 'Night', 'Available', '131', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W325', 'Tanya Yadav', 'Shift Supervisor', 'Morning', 'On Task', '799', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W326', 'Kiran Nair', 'Unloader', 'Afternoon', 'On Task', '306', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W327', 'Amit Kulkarni', 'Unloader', 'Afternoon', 'On Task', '538', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W328', 'Manish Sharma', 'Loader', 'Night', 'On Break', '721', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W329', 'Sanjay Kumar', 'Shift Supervisor', 'Night', 'On Break', '667', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W330', 'Sanjay Kumar', 'Shift Supervisor', 'Morning', 'Available', '373', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W331', 'Sonia Joshi', 'Unloader', 'Night', 'Available', '137', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W332', 'Neha Pawar', 'Shipping Associate', 'Night', 'On Break', '490', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W333', 'Asha Hegde', 'Inventory Clerk', 'Night', 'Available', '138', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W334', 'Aditya Sawant', 'Shipping Associate', 'Morning', 'Available', '209', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W335', 'Sunita Agarwal', 'Unloader', 'Morning', 'Available', '817', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W336', 'Suma Naik', 'Shift Supervisor', 'Night', 'Available', '374', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W337', 'Vandana Gowda', 'Shipping Associate', 'Night', 'Available', '463', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W338', 'Deepak Naik', 'Forklift Operator', 'Morning', 'On Task', '16', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W339', 'Kavya Rao', 'Unloader', 'Morning', 'Available', '454', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W340', 'Sanjay Kumar', 'Forklift Operator', 'Night', 'On Break', '506', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W341', 'Vidya Sharma', 'Packer', 'Afternoon', 'On Task', '657', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W342', 'Kavya Rao', 'Shipping Associate', 'Night', 'On Task', '926', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W343', 'Aditi Kulkarni', 'Quality Inspector', 'Afternoon', 'Available', '969', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W344', 'Sanjay Kumar', 'Unloader', 'Afternoon', 'Available', '348', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W345', 'Arjun Reddy', 'Loader', 'Night', 'On Break', '780', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W346', 'Tarun Srivastava', 'Shipping Associate', 'Night', 'Available', '382', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W347', 'Swapnali Pawar', 'Picker', 'Afternoon', 'Available', '586', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W348', 'Dinesh Jadhav', 'Inventory Clerk', 'Afternoon', 'Available', '926', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W349', 'Sumit More', 'Shift Supervisor', 'Morning', 'Off Shift', '687', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W350', 'Rasika Deshmukh', 'Packer', 'Night', 'Available', '420', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W351', 'Aditi Kulkarni', 'Shipping Associate', 'Afternoon', 'Available', '673', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W352', 'Ravi Kumar', 'Packer', 'Afternoon', 'Available', '206', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W353', 'Amit Kulkarni', 'Quality Inspector', 'Morning', 'Off Shift', '865', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W354', 'Manoj Sharma', 'Receiving Associate', 'Night', 'Available', '937', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W355', 'Pradeep Rao', 'Receiving Associate', 'Night', 'Available', '791', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W356', 'Meena Murthy', 'Shift Supervisor', 'Afternoon', 'On Break', '177', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W357', 'Pratik Bhosale', 'Packer', 'Afternoon', 'On Break', '717', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W358', 'Aniket Shinde', 'Receiving Associate', 'Morning', 'On Break', '555', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W359', 'Gauri Bhosale', 'Packer', 'Morning', 'On Task', '107', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W360', 'Monika Yadav', 'Inventory Clerk', 'Afternoon', 'On Task', '703', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W361', 'Pankaj Agarwal', 'Quality Inspector', 'Afternoon', 'On Task', '679', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W362', 'Ravi Kumar', 'Receiving Associate', 'Afternoon', 'Available', '824', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W363', 'Poonam Mishra', 'Inventory Clerk', 'Night', 'On Break', '76', '27', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W364', 'Simran Srivastava', 'Packer', 'Night', 'Available', '297', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W365', 'Nandini Gowda', 'Unloader', 'Night', 'Available', '242', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W366', 'Simran Srivastava', 'Unloader', 'Morning', 'Available', '715', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W367', 'Ganesh Hegde', 'Packer', 'Night', 'Available', '887', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W368', 'Rasika Deshmukh', 'Shipping Associate', 'Morning', 'On Break', '440', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W369', 'Swathi Shetty', 'Picker', 'Afternoon', 'Off Shift', '357', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W370', 'Arjun Reddy', 'Inventory Clerk', 'Morning', 'Available', '178', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W371', 'Ganesh Hegde', 'Packer', 'Night', 'On Break', '819', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W372', 'Tushar Srivastava', 'Shipping Associate', 'Afternoon', 'Available', '880', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W373', 'Neha Pawar', 'Shipping Associate', 'Afternoon', 'On Break', '701', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W374', 'Pradeep Rao', 'Loader', 'Afternoon', 'Available', '730', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W375', 'Keerthi Murthy', 'Shipping Associate', 'Afternoon', 'Available', '679', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W376', 'Monika Yadav', 'Quality Inspector', 'Afternoon', 'Available', '760', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W377', 'Ashwini Sawant', 'Loader', 'Morning', 'Available', '246', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W378', 'Manoj Sharma', 'Quality Inspector', 'Morning', 'Available', '880', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W379', 'Vijay Rao', 'Shift Supervisor', 'Night', 'On Break', '886', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W380', 'Sanjay Kumar', 'Picker', 'Morning', 'On Task', '645', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W381', 'Ganesh Hegde', 'Receiving Associate', 'Night', 'On Task', '602', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W382', 'Rutuja Kulkarni', 'Loader', 'Night', 'On Task', '743', '25', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W383', 'Dinesh Jadhav', 'Forklift Operator', 'Morning', 'On Break', '854', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W384', 'Manoj Sharma', 'Unloader', 'Afternoon', 'Available', '619', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W385', 'Ravi Kumar', 'Unloader', 'Morning', 'On Task', '68', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W386', 'Nikhil Hegde', 'Loader', 'Afternoon', 'On Task', '779', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W387', 'Ajay Reddy', 'Forklift Operator', 'Night', 'On Break', '633', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W388', 'Shruti Sharma', 'Quality Inspector', 'Morning', 'On Task', '730', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W389', 'Vaibhav Deshpande', 'Loader', 'Night', 'Available', '603', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W390', 'Shweta Joshi', 'Quality Inspector', 'Afternoon', 'Available', '860', '24', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W391', 'Manoj Sharma', 'Inventory Clerk', 'Afternoon', 'Available', '610', '24', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W392', 'Arjun Reddy', 'Receiving Associate', 'Afternoon', 'Available', '387', '28', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W393', 'Gaurav Deshpande', 'Shift Supervisor', 'Morning', 'Available', '203', '27', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W394', 'Gaurav Deshpande', 'Loader', 'Night', 'On Task', '343', '26', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W395', 'Prashanth Naik', 'Picker', 'Night', 'On Break', '57', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W396', 'Anil Murthy', 'Unloader', 'Afternoon', 'On Task', '802', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W397', 'Manoj Sharma', 'Picker', 'Morning', 'On Task', '697', '25', 'Male');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W398', 'Kavita Mishra', 'Picker', 'Morning', 'On Task', '380', '28', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W399', 'Manasi Shinde', 'Loader', 'Morning', 'Available', '863', '26', 'Female');
INSERT INTO warehouse_workers_final (worker_id, name, role, shift, status, tasks_completed, age, gender) VALUES ('W400', 'Tushar Srivastava', 'Shipping Associate', 'Night', 'On Task', '548', '26', 'Male');
